### ISSUE TITLE
Changes needed for the sensor names?

### ISSUE THREAD

**Issue by wwwescape** [id628/flic2hass#3]
Today, when I logged into my Home Assistant instance, I saw a repair suggestion:

<img width="431" alt="image" src="https://github.com/id628/flic2hass/assets/651507/d6541579-444d-467d-85e5-9f3627d2923b">

Do we need to make any changes to `main.js`?

**Comment by id628** [comment]
Yes, I noticed that 2023.8 has some breaking changes in MQTT Auto Discovery.  I'm guessing this is related.

It looks like we have until February 2024 to fix this... I'm not too worried.
