### ISSUE TITLE
Support for realtime Down/Up State

### ISSUE THREAD

**Issue by alexander-cato** [id628/flic2hass#4]
It would be great to have down / up state reported in addition to "click",  "double_click", "hold".
Often "hold" is not enough information.

Use case example: Dimming a light while held down by 2% every 200ms. Stop dimming upon release.
Presently this is impossible to accomplish with just a "hold" reported, then automatically returning to "ok"

We should be able to use: `buttonManager.on("buttonUp")` & `buttonManager.on("buttonDown")` to achieve this.

**Comment by alexander-cato** [comment]
Another potential solution is after sending the "hold" status, don't return to "ok"  until buttonManager.on("buttonUp).

**Comment by id628** [comment]
Merged your code!
